server.port=8081

# MongoDB Configuration (Connects lazily to local MongoDB server on port 27017 with 2s timeout)
spring.data.mongodb.uri=mongodb://localhost:27017/smartfit_db?serverSelectionTimeoutMS=2000
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
smartfit.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
smartfit.jwt.expiration-ms=86400000

# Logging & Security
logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.security=INFO
